### ISSUE TITLE
Use WebHighlightTabs moduleIssuses 

### ISSUE THREAD

**Issue by czRequiem** [LlamachantTechnology/llamachantframeworkxaf#1]
![image](https://user-images.githubusercontent.com/18690818/41387113-cf146eec-6fb7-11e8-80bd-035627721cbd.png)
I  click  NextObjectAction or PreviousObjectAction after the view  group table caption not refresh .
Thanks for any help.
Peter

**Comment by Llamachant** [comment]
Thanks Peter. This issue has been addressed and checked in.

**Comment by czRequiem** [comment]
Thanks a lot

**Comment by czRequiem** [comment]
![image](https://user-images.githubusercontent.com/18690818/41445756-2b9cb7b6-707e-11e8-92bc-3f163a0f1535.png)
You can add this line code
If the collection has no value, the collection caption will not be updated and will remain the value of the previous object.

**Comment by Llamachant** [comment]
New change has been published. We set the tab style back to non-bolded when the count is zero.
